[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing settings
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15, fail_on_revert = false }

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Coverage settings
coverage_exclude = ["test/**/*", "script/**/*"]

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

# RPC endpoints
[rpc_endpoints]
monad-testnet = "${MONAD_TESTNET_RPC}"
monad-mainnet = "${MONAD_MAINNET_RPC}"

# Etherscan configuration
[etherscan]
monad-testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet-explorer.monad.xyz/api" }
monad-mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.monad.xyz/api" }

# Profile for CI
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

# Profile for intense testing
[profile.intense]
fuzz = { runs = 50000 }
invariant = { runs = 5000, depth = 25 }